spring.application.name=carsapp

spring.datasource.url=jdbc:postgresql://localhost:5432/Cars
spring.datasource.username=postgres
spring.datasource.password=passwd

spring.flyway.baseline-version=0

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.results=DEBUG